# Generated by Django 6.0.5 on 2026-06-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
